### ISSUE TITLE
Error on update to latest 

### ISSUE THREAD

**Issue by Aramousa** [Phronesis255/NMW-Test1#1]
it prompts 

> ` pip install -r requirements.txt
Collecting en-core-web-sm==3.5.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 2.0 MB/s eta 0:00:00
Requirement already satisfied: streamlit in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.40.1)
Requirement already satisfied: googlesearch-python in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.2.5)
Requirement already satisfied: requests in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (2.32.3)
Requirement already satisfied: bs4 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (0.0.2)
Requirement already satisfied: pandas in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (2.2.3)
Requirement already satisfied: numpy==1.24.3 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (1.24.3)
Requirement already satisfied: spacy==3.5.0 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (3.5.0)
Requirement already satisfied: thinc==8.1.7 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (8.1.7)
Requirement already satisfied: scikit-learn in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (1.5.2)
Requirement already satisfied: matplotlib in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (3.9.2)
Requirement already satisfied: urllib3 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (2.2.3)
Requirement already satisfied: altair in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (5.4.1)
Requirement already satisfied: streamlit-quill in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (0.0.3)
Collecting google-search-results
  Using cached google_search_results-2.4.2.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting nltk
  Using cached nltk-3.9.1-py3-none-any.whl (1.5 MB)
Collecting sentence-transformers
  Using cached sentence_transformers-3.3.1-py3-none-any.whl (268 kB)
Collecting transformers
  Using cached transformers-4.47.0-py3-none-any.whl (10.1 MB)
Collecting people_also_ask
  Using cached people_also_ask-1.1.0.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Collecting typing
  Using cached typing-3.7.4.3.tar.gz (78 kB)
  Preparing metadata (setup.py) ... done
Collecting torch
  Using cached torch-2.5.1-cp310-cp310-manylinux1_x86_64.whl (906.4 MB)
Collecting ssl
  Using cached ssl-1.16.tar.gz (33 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tq6x017_/ssl_f11fd751dbde489591df53b83a305e5d/setup.py", line 33
          print 'looking for', f
          ^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
` 
after update using requirements.txt

**Comment by Phronesis255** [comment]
Hi

I think it should work now. I updated the requirements.txt and removed "ssl" which should resolve the issue. Please add any new issues and I'll try to fix them quickly.

**Comment by Aramousa** [comment]
just get requirement.exe ?

**Comment by Aramousa** [comment]
again Error

> `Collecting people_also_ask
  Using cached people_also_ask-1.1.0.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Collecting typing
  Using cached typing-3.7.4.3.tar.gz (78 kB)
  Preparing metadata (setup.py) ... done
Collecting torch
  Using cached torch-2.5.1-cp310-cp310-manylinux1_x86_64.whl (906.4 MB)
ERROR: Could not find a version that satisfies the requirement string (from versions: none)
ERROR: No matching distribution found for string
`

**Comment by Phronesis255** [comment]
Okay so I updated the requirements.txt again, and I think this time it's gonna run! 

You can update requirements.txt or just edit it locally and remove "string" or just delete the code in requirements.txt and paste this:

```
streamlit
googlesearch-python
requests
bs4 
pandas 
numpy==1.24.3
spacy==3.5.0
thinc==8.1.7
scikit-learn
matplotlib
urllib3
altair
streamlit-quill
google-search-results
nltk
sentence-transformers
transformers
people_also_ask
typing
torch
sentence_transformers


https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl

```

**Comment by Aramousa** [comment]
its ok.

**Comment by Phronesis255** [comment]
Great. Thanks for working through it.
